### ISSUE TITLE
Weekly Meetings and Demos page updated for Sprint 1

### ISSUE THREAD

**Issue by AustinGrey** [TransparentGovernanceUofA/TransparentGov#10]
1) Meeting minutes on the team wiki.
2) Evidence that the team works well with the client.
3) The team works well with the TA (asks questions/advice, reports
progress meaningfully, addresses feedback).
4) Team has made real progress since the beginning.

**Comment by jbbela** [comment]
Meeting minutes on wiki are up to date - includes all client meetings and weekly meetings
