### ISSUE TITLE
Hosting site on Cybera

### ISSUE THREAD

**Issue by Aquafina99** [TransparentGovernanceUofA/TransparentGov#17]

**Comment by jbbela** [comment]
test with basic django using nginx, gunicorn, and supervisor now running on cybera

**Comment by jbbela** [comment]
admin and drf css does not load; will look into issue

**Comment by jbbela** [comment]
Nginx now serves static files correctly.

**Comment by Aquafina99** [comment]
We now host our site on Cybera
