### ISSUE TITLE
Determine how PDF scraper will interface with Elastic Search

### ISSUE THREAD

**Issue by AustinGrey** [TransparentGovernanceUofA/TransparentGov#22]
PDF team and Elastic search team need to meet to discuss and make sure Elastic search can hold and return the information scraped from the PDFs

**Comment by AustinGrey** [comment]
In discussion with Julienne, the scraper needs to output JSON format for elastic search to handle. This was the result of the discussion:
```
{
  "title": "GFC Meeting Materials 2015-05-09",
  "date": "2015-05-09",
  "committee": "GFC tuition committee",
  "subsection": "meeting minutes",
  "presenters": [ {"name": "Joe Doe"}, {"name": "Sally Jane"}]
  "pages": [
    {
      "text": "Committee meets to blah blah blah......"
      ("motions": [ and then a list of motion objects?])
      ("keywords": [ and then a list of scraped key words?])
    },
    {
      "text": "continuing from the previous page we motion to......"
    }
  ]
  "items": [
    {
      "index_in_pdf": 1 // How to refer to this issue from within the same pdf - should match the glossary
      "separate_index": 2983 // How to link this issue if it appears in multiple different pdfs
      "title": "Tuition discussion papers 2017"
      "pages_start": 4
      "pages_end": 8
    },
    {
      "text": "continuing from the previous page we motion to......"
    }
  ]
}
```

Excerpt from the discussion
Julienne - Today at 12:41 PM
Yeah that looks great! The only thing is that most of the meeting minutes have a field called presenters? Maybe that should be added?
Austin C - Today at 12:43 PM
Okay, then a list field of presenters, and a list for for items too perhaps? Theres going to be a lot of manual work here I feel but we will see what can be accomplished. I don't know how far Greg has got.
I'm studying for a monday midterm rn, and then my plan was to get cooking on those sprint 2 github issues like redo-ing the requirements, documentation, diagrams and addressing feedback. But if Greg can't get to this in time and you need it let me know and I'll get to that first instead.

**Comment by gsgould** [comment]
Finalized

`{
  "title": "GFC Faculties Council",
  "date": "2015-05-09",
  "committee": "General Faculties Council",
  "time": "2:00PM - 4:00PM"
  "location": "University Hall",
    {
        "subsection": "Opening Session",
        {
            "items": [
                        {
                        "index_in_pdf": 1 // How to refer to this issue from within the same pdf - should match the glossary
                      
                        "separate_index": 2983 // How to link this issue if it appears in multiple different pdfs // is this part of our MVP?
                      
                        "Title": "Tuition discussion papers 2017"
                      
                        "pages_start": 4
                      
                        "pages_end": 8
                      
                        "Text": "continuing from the previous page we motion to......"
                      
                        "Presenters": [ {"name": "Joe Doe"}, {"name": "Sally Jane"}]
                      
                        "Motions": [ {"Motion": "That General Faculties Council approve the Agenda", "Carried": "True", "Content":"Materials before members are conained within"}])

                        "Keywords": [{"Keywords", "Of", "Interest"])
                      
                        "Discussion": "Following an Indigneous welcome, etc")
                      
                        "Purpose": "continuing from the previous page we motion to......"
                      } ]
        }
    }
}

 `
