### ISSUE TITLE
Create a basic advanced search, similar to beartracks.

### ISSUE THREAD

**Issue by VukR** [TransparentGovernanceUofA/TransparentGov#68]
Terms to search by:
- [x] Committee 
- [x] Date
- [x] People

Load from elastic search, possible dynamically 

- [x] Committee
- [x] People

#108 add date pickers

**Comment by Jolton** [comment]
Terms to search by:
- [ ] Committee 
- [ ] Date
- [ ] People


Load Committee and people from elastic search, possible dynamically load

#108 add date pickers
