### ISSUE TITLE
create basic advanced search layout

### ISSUE THREAD

**Issue by AustinGrey** [TransparentGovernanceUofA/TransparentGov#74]
layout the advanced search in bootstrap to better match the other new layouts

**Comment by AustinGrey** [comment]
#68 will implement the functional components, once that's done this issue will tackle organization and style

**Comment by VukR** [comment]
I did some work for this. The latest #67 branch or pull into dev and see what I've done.

**Comment by AustinGrey** [comment]
Awaiting pull #82 to merge layout into dev
