### ISSUE TITLE
Improve search to handle more complicated query

### ISSUE THREAD

**Issue by Aquafina99** [TransparentGovernanceUofA/TransparentGov#84]

**Comment by jbbela** [comment]
Match is currently based on prefix. For more complicated searches (ie. "nurse" -> "nursing"), then **keywords would need to be identified** and put into Elasticsearch.

**Comment by jbbela** [comment]
Needs to match multiple terms to documents.

ie., Search for: 'budget tuition'
Should bring up documents with both budget and tuition mentioned.

**Comment by jbbela** [comment]
Look into Lemmatization and Stemmers
