### ISSUE TITLE
Implement highlighted search term

### ISSUE THREAD

**Issue by Aquafina99** [TransparentGovernanceUofA/TransparentGov#86]
When searching all searching terms should be highlighted

**Comment by jbbela** [comment]
From Elasticsearch, the terms to be highlighted are wrapped with <em> and </em>.
For example, when searching "budget", all mentions of budget in a search result will be highlighted as: <em>budget</em>

**Comment by jbbela** [comment]
When searching, results return highlighted query term mentions in Title and Description as expected.
Looks good!
